### ISSUE TITLE
Crash-el az app

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#1]
**Írd le, hogy mit tapasztaltál**
Az inventory crashel és az együttműködések alatt nem mindig jelennek meg a partnerek kártyái.

**Hogyan tudjuk reprodukálni / előidézni?**
1. Menj az 'Inventory' képernyőre.
2. Várj pár másodpercet.
3. Az app leáll.

**Mi az elvárt viselkedés?**
Ne álljon le az app, jelenjen meg a megfelelő tartalom.

**A következő információk nagyon fontosak:**
- OS verzió: Android 11
- Készülék: Xiaomi Redmin Note 9 Pro
- App Verzió: 0.0.1
- Internet: WIFI, 4G

**Screenshots**
![319913909_618346453398984_28360182504365453_n](https://user-images.githubusercontent.com/20354967/209335385-f317d0a8-932a-442f-88f5-41e6e2fd6bf5.jpg)
![321780764_5740249619385499_6093117833062927897_n](https://user-images.githubusercontent.com/20354967/209335399-44caba1d-23d6-45e5-b79a-9648f222844e.jpg)

**Comment by prefector** [comment]
Oneplus 9, android 13 - nincs ilyen hiba

**Comment by iujlaki** [comment]
Igen, javítottuk egyből ahogy kiment a verzió, köszi. 
@DavidKoth1 ugye ez már nem áll fen nálad sem?

**Comment by DavidKoth1** [comment]
@iujlaki 0.0.2-ben már nálam sem jön elő.
