### ISSUE TITLE
Másolás gomb (javaslat)

### ISSUE THREAD

**Issue by OlevO1** [teamcodeyard/thevrapp-tracker#10]
![3F322118-5A53-4508-ACCA-8A9E9AEE44E7](https://user-images.githubusercontent.com/95526844/209576786-dfcf1c91-99d0-4d03-8052-32492bbb274d.png)

**Bármi más amivel kiegészítenéd**
Kerülhetne ide egy másolás gomb a kuponokhoz

**Comment by iujlaki** [comment]
@OlevO1 köszi, igen ez még hiányos amit szeretnénk hogy a kártyák átnavigáljanak az adott oldalra, de a másolás sem rossz ötlet. 
Ezen törjük még a fejünket, ugye tappolásra a kártyák mozognak így valahogy máshogy kell megoldani.

**Comment by iujlaki** [comment]
Megoldottuk a navigálást, másolás nem lesz mivel elég rövid kódok illetve nem nagyon tudjuk esztétikailag szépen elhelyezni. Lesznek olyan linkek amiben eleve benne lesznek a kódok
