### ISSUE TITLE
Többszöri értesítés

### ISSUE THREAD

**Issue by 0xbalazstoth** [teamcodeyard/thevrapp-tracker#11]
**Írd le, hogy mit tapasztaltál**
Többszöri értesítés egy új hírről.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Hírek' képernyőre.
2. Nézd meg az értesítéseid.
3. Lásd a hibát

**Mi az elvárt viselkedés?**
Egyszeri értesítés egy adott hírről.

**Screenshots**
![IMG_0488](https://user-images.githubusercontent.com/12668764/209654468-0182453d-764b-4997-95df-e1640feffc41.jpg)
![IMG_0487](https://user-images.githubusercontent.com/12668764/209654475-c1f545c2-16c6-4faf-9e6d-1f51bf298ecf.PNG)

**A következő információk nagyon fontosak:**
- OS verzió: 16.2
- Készülék: iPhone 13
- App Verzió: 0.1.0 (build 7)
- Internet: WIFI, 4G

**Comment by ntfargo** [comment]
it's not a bug it's a feature.

**Comment by vorosvezer** [comment]
+1, Nekem az a földöntúli blep hang is négyszer bleppelt
Ios: 16.2
SE 2020
0.1.0(build 7)

**Comment by Nickname1122** [comment]
+1, értesítés hang mindegyiknél volt, viszont órára nem kaptam meg
iOS: 16.3 (public beta), watchOS 9.0
iPhone 12
0.1.0(build 7)

**Comment by iujlaki** [comment]
A hiba iOS-en volt, viszont backenden is levédtük, hogy ne forduljon el.
@Nickname1122 az órára értesítést meg tudod nézni majd mégegyszer, illetve ellenőrizni hogy engedélyezve van e a Watch alkalmazásban?

**Comment by Nickname1122** [comment]
Megnéztem, engedélyezve van az értesítés órán is, ami amúgy egy Series 7

**Comment by Nickname1122** [comment]
Update: ma már kaptam órára is értesítést @iujlaki, bár nem tudom, hogy az új verzió után vagy elõtt, mert családi program volt.

**Comment by iujlaki** [comment]
Köszi, zárom az issue-t, nekem mindig jön órára is
