### ISSUE TITLE
Swipe right visszalépéshez a beállításokból (Javaslat)

### ISSUE THREAD

**Issue by Nickname1122** [teamcodeyard/thevrapp-tracker#12]
![image](https://user-images.githubusercontent.com/52052947/209662978-1f01c0a7-577b-4a4f-9dc4-b8055c341bd3.png)

**Bármi más amivel kiegészítenéd**
Kényelmi funkció, mint ahogy bármelyik másik alkalmazásban iOS-ben, visszalépés az elõzõ képernyõre egy jobbra húzással a képernyõ bal szélétõl a beállítások menüben.

**Comment by iujlaki** [comment]
12-es buildbe bekerült
