### ISSUE TITLE
Statikus eltelt idõ

### ISSUE THREAD

**Issue by Nickname1122** [teamcodeyard/thevrapp-tracker#13]
**Írd le, hogy mit tapasztaltál**
Az értesítés fülön az eltelt idõ statikus és a szövegezés nem jó.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj az 'Értesítések' képernyőre
2. Lásd a hibát

**Mi az elvárt viselkedés?**
Megfelelõ szövegezés és helyes eltelt idõ mutatása.

**Screenshots**
![image](https://user-images.githubusercontent.com/52052947/209663977-2acd3786-9f07-47ff-b073-469a4454e898.png)

**A következő információk nagyon fontosak:**
- OS verzió: iOS 16.3 (public beta)
- Készülék: iPhone 12
- App Verzió: 0.1.0(7)
- Internet: 4G

**Comment by Nickname1122** [comment]
Update:

**Írd le, hogy mit tapasztaltál**
A szövegezés már jó, viszont most az 'Értesítések' megnyitása óta eltelt idõt mutatja, illetve, ha újakat húz le, akkor azok 0-tól kezdenek.

**Screenshots**
https://user-images.githubusercontent.com/52052947/209918609-8442c01e-dfc4-4a3a-8c35-b756c088d19a.MOV

App Verzió: 0.1.0(8)

**Comment by iujlaki** [comment]
Ez elvileg már javult ahogy beszéltük is Discordon.
