### ISSUE TITLE
Nem töltbe a 'Hírek' fül

### ISSUE THREAD

**Issue by Nickname1122** [teamcodeyard/thevrapp-tracker#14]
**Írd le, hogy mit tapasztaltál**
Rányomtam az értesítésre és az app megnyílása után nem töltöttek be a hírek.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Kattincs rá egy értesítésre
2. Várd meg, amíg megnyílik az app
3. Lásd a hibát

**Mi az elvárt viselkedés?**
Töltsenek be a hírek az èrtesítésbõl való megnyitás után

**Screenshots**
![image](https://user-images.githubusercontent.com/52052947/209677616-f8cb3404-d26e-41db-9fa7-781066da1017.png)

**A következő információk nagyon fontosak:**
- OS verzió: iOS 16.3 (public beta)
- Készülék: iPhone 12
- App Verzió: 0.1.0
- Internet: 4G

**Comment by iujlaki** [comment]
Javítva 🙏
