### ISSUE TITLE
Hírek fülön vissza a tetejére gomb

### ISSUE THREAD

**Issue by eletmuvesz** [teamcodeyard/thevrapp-tracker#15]
**Írd le, hogy mit tapasztaltál**
Ha letekerek a híreknél, jól jönne  az, ha visszaugrana a tetejére, ha újra rányomok a hírek fülre.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a Hírek képernyőre
2. Görgess le.
3. Lásd a hibát

**Mi az elvárt viselkedés?**
A hírek fülre kattintva ugorjon fel a tetejére az oldalnak. Igaz, hogy ha a notch alá tappolunk is felugrik, de így kényelmesebb lenne.

**A következő információk nagyon fontosak:**
- OS verzió [iOS 16.2]
- Készülék [iPhone 13]
- App Verzió [0.1.0(7)]

**Bármi más amivel kiegészítenéd**
Amúgy nagyon szuper az app, az értesítési hang először megzavart, mert azthittem Steam-en írtak, aztán rájöttem hogy évek óta nem is használom. :D

**Comment by iujlaki** [comment]
Igen, ez mindenképpen benne lesz mert én is gyakran használom, köszi hogy felvetted 🙏
