### ISSUE TITLE
Hiányzó időbélyeg 

### ISSUE THREAD

**Issue by iujlaki** [teamcodeyard/thevrapp-tracker#16]
**Írd le, hogy mit tapasztaltál**
A bejegyzéseknél eltűnik az idő bélyeg ha 1 napnál régebbi

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a Hírek képernyőre
2. Görgess le addig amíg 24 óránál régebbi bejegyzést találsz

**Mi az elvárt viselkedés?**
Legyen kiírva, hogy X napja 🙃

**Screenshots**
![image](https://user-images.githubusercontent.com/429180/209837526-5301d655-8b6c-441f-b858-5d4488827f68.png)

**A következő információk nagyon fontosak:**
Android

**Comment by DavidKoth1** [comment]
Én nem látok benne logikát. Csináltam pár screenshotot és próbáltam belőni a határértékeket.
![Screenshot_2022-12-28-17-24-26-068_hu thevr fallback](https://user-images.githubusercontent.com/20354967/209842605-df348db2-ce45-4d43-8c2c-c72f098b8e76.jpg)
![Screenshot_2022-12-28-17-24-34-136_hu thevr fallback](https://user-images.githubusercontent.com/20354967/209842625-4985e0e6-fd2f-424a-a9b6-0c5e6eb8e4e4.jpg)
![Screenshot_2022-12-28-17-24-48-564_hu thevr fallback](https://user-images.githubusercontent.com/20354967/209842641-396b125e-3989-41f1-a299-6432ce2eba85.jpg)
![Screenshot_2022-12-28-17-25-09-829_hu thevr fallback](https://user-images.githubusercontent.com/20354967/209842649-ab56e546-cc1e-4762-bea4-e53dc07fa239.jpg)

**Comment by DavidKoth1** [comment]
Az értesítéseknél is hiányoznak az időbélyegek, nem csak a hirek screent érinti ez. 
A csatolt képeken az utolsó podcast postjának (a hírekben) és a hozzá tartozó időbélyeg között van 3 óra eltérés. Az értesítéseknél 3 órával többet ír.
![Screenshot_2022-12-29-14-34-55-907_hu thevr fallback](https://user-images.githubusercontent.com/20354967/209961834-8ede7855-ccd5-454d-a3d8-da00c3058174.jpg)
![Screenshot_2022-12-29-14-35-15-573_hu thevr fallback](https://user-images.githubusercontent.com/20354967/209961863-d58ae63d-9bef-4e9d-afd5-eeeb5d3c9e28.jpg)
![Screenshot_2022-12-29-14-35-25-584_hu thevr fallback](https://user-images.githubusercontent.com/20354967/209961876-fd9fbe3c-4782-4703-ba73-24eb1c237798.jpg)

**Comment by botix4** [comment]
Nem látom leírva, így leírom. Az idő bélyeg hiánya mind a két fülön(hírek és értesítések) ugyan azoknál hiányzik. És ha új értesítés/poszt fut be, akkor változik, hogy melyikeknél nincs.

**Comment by DavidKoth1** [comment]
0.0.4-ben már javítva mindkét képernyőn.
