### ISSUE TITLE
Ismétlõdés a 'Hírek'-ben

### ISSUE THREAD

**Issue by Nickname1122** [teamcodeyard/thevrapp-tracker#18]
**Írd le, hogy mit tapasztaltál**
A 10 legfrissebb bejegyzést 2x húzza le a backend.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Hírek' képernyőre
2. Görgess le
3. Lásd a hibát

**Mi az elvárt viselkedés?**
Ne legyen 2x lehúzva a 10 legfrissebb bejegyzés

**Screenshots**
https://user-images.githubusercontent.com/52052947/209870054-95402c93-3a0b-4021-bff5-d608a69f5629.MOV

**A következő információk nagyon fontosak:**
- OS verzió: iOS 16.3 (public beta)
- Készülék: iPhone 12
- App Verzió: 0.1.0 (8)
- Internet: 4G

**Comment by iujlaki** [comment]
0.1.0 (build 9)-esben javítva
