### ISSUE TITLE
Értesítéseket nem lehet bekapcsolni

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#2]
**Írd le, hogy mit tapasztaltál**
Hiába próbálom bekapcsolni az értesítéseket, nem történik semmi, hiába tappolok a kapcsolóra.

**Hogyan tudjuk reprodukálni / előidézni?**
1.Menj az értesítések képernyőre.
2. Tappolj valamelyik kapcsolóra (Rendszer értesítések, Menetrend vagy Social)
3. Nem történik semmi, a kapcsoló nem vált státuszt.

**Mi az elvárt viselkedés?**
Ha valamelyik kapcsolóra tappolok, akkor annak státusza változzon meg. On-ról off-ra illetve fordítva.

**Screenshots**
Ha tudsz akkor csatolj képernyőképet, hogy megkönnyítsd a munkánkat.

**A következő információk nagyon fontosak:**
- OS verzió: Android 11
- Készülék: Xiaomi Redmin Note 9 Pro
- App Verzió: 0.0.1
- Internet: WIFI, 4G

**Comment by iujlaki** [comment]
Ez szándékosan van kikapcsolva mert a push értesítések még nincs bekötve
