### ISSUE TITLE
Beállítások toggle switch bug

### ISSUE THREAD

**Issue by Errorhybrid** [teamcodeyard/thevrapp-tracker#21]
**Írd le, hogy mit tapasztaltál**
Beállításokban a toggle switch úgy gondolom, hogy vizuálisan nem működik - tegnap egyszer rányomtam, nem váltott át se jobb oldalra a kis pötty és színt se váltott, de értesítéseket kaptam, így szerintem csak vizuális a hiba talán

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a Beállítások képernyőre
2. Tappolj a bármelyik toggle gombra
4. Lásd a hibát

**Mi az elvárt viselkedés?**
A toggle switchnek pozíciót és színt kellene váltania

**Screenshots**

https://user-images.githubusercontent.com/106850722/209967477-eca99ef9-a28d-4e11-be8f-751c32030e9d.mp4

**A következő információk nagyon fontosak:**
- OS verzió: Android 12 SKQ1.211006.001
- Készülék: POCO F2 Pro
- App Verzió: 0.0.2
- Internet: Wi-Fi

**Comment by prefector** [comment]
Ezek egyelőre le vannak tiltva

**Comment by iujlaki** [comment]
az értesítések testreszabása még nem elérhető
