### ISSUE TITLE
Menetrendben nincsenek ütemezések beállítva

### ISSUE THREAD

**Issue by DaniAbo218** [teamcodeyard/thevrapp-tracker#22]
A menetrendben nincsenek ütemezve a streamek. A novemberi streamek még ott vannak, de a decembertől mindenhol csak annyit ír, hogy ezen a napon nincs közvetítés.

- OS verzió: miui global 12.0.20
- Készülék: xiaomi redmi 9at
- App Verzió: 0.0.2
- Internet: WIFI

**Comment by 0xbalazstoth** [comment]
Ez nem hiba, csupán a srácok (thevr) még nem vettek fel semmit a menetrendbe.

**Comment by iujlaki** [comment]
A menetrendet a weboldalról szedjük: https://thevr.hu/menetrend/
Még ott sincs ütemezve semmi.
