### ISSUE TITLE
Menetrend idõpontok

### ISSUE THREAD

**Issue by Nickname1122** [teamcodeyard/thevrapp-tracker#24]
**Írd le, hogy mit tapasztaltál**
A stream-ek kezdési és befejezési idõpontjai elcsúsznak 1 órával

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Menetrend' képernyőre
2. Válts át a jan. 02-08.-ai hétre
3. Válts keddre
4. Lásd a hibát

**Mi az elvárt viselkedés?**
Legyen szinkronban az weboldali menetrenddel

**Screenshots**
![image](https://user-images.githubusercontent.com/52052947/210055897-61d4328f-310c-4e04-bca5-7355de90ce5c.png)

**A következő információk nagyon fontosak:**
- OS verzió: iOS 16.3 (public beta)
- Készülék: iPhone 12
- App Verzió: 0.1.0 (8)
- Internet: 4G

**Comment by DavidKoth1** [comment]
Androidon is ugyanez a helyzet. Az app szerint minden 1 órával később kezdődik. Visszamenőleg is ebben az évben, nem csak januárban van elcsúszva.

- OS verzió: Android 11
- Készülék: Xiaomi Redmi Note 9 Pro
- App Verzió: 0.0.2
- Internet: WIFI, 4G

**Comment by cubixx** [comment]
Nálam is hasonló a helyzet. Szerintem idozonaval vagy DaylightSavingTime-al kapcsolatos a dolog, mert nálam 2 órával mutat többet.

Idozonam: EET, UTC+2
App verzió: 0.0.3
Android 9

**Comment by DavidKoth1** [comment]
0.0.4-ben javítva.
