### ISSUE TITLE
Beállitások

### ISSUE THREAD

**Issue by Leviih01** [teamcodeyard/thevrapp-tracker#25]
**Írd le, hogy mit tapasztaltál**
Egyértelműen írd le kérlek, hogy milyen hibát találtál.
Beállításoknál nem lehet semmit bekapcsolni
**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a Beállításokképernyőre
2. Tappolj a  Kapcsolókra
3. Itt a Hiba

**Mi az elvárt viselkedés?**
A kapcsolóknak müködnie kellene

**Screenshots**
Videót csináltam róla: 
https://youtube.com/shorts/DLhRQT5D77s?feature=share

**A következő információk nagyon fontosak:**
- OS verzió: Android 13
- Készülék: Samsung Galaxy A32 5G
- App Verzió: 0.0.2
- Internet:4G+

**Bármi más amivel kiegészítenéd**
Kíváncsiak vagyunk a véleményedre, kérlek írd le, hogy mit gondolsz az alkalmazásról?
Ezen  a hibán kivül teljesen jó.

**Comment by iujlaki** [comment]
Jelenleg szándékosan vannak letiltva a beállítások módosítása, ezt az issue-t itt hagyom hogy lássák (páran már jelezték) ez nem hiba :) 
Köszi
