### ISSUE TITLE
Shop visual bug

### ISSUE THREAD

**Issue by aTube41** [teamcodeyard/thevrapp-tracker#26]
Írd le, hogy mit tapasztaltál
Shop fül legaljára görgetve az utolsó felirat fele mindig ki van takarva. A termék családot jelző felső ikon nem mindig csukódik össze. Lassu görgetéssel teljes méretben marad.

Hogyan tudjuk reprodukálni / előidézni?
Ezekkel a lépésekkel:
1. Menj a kezdő képernyőre
2. Tappolj a shop gombra
3. Görgess le teljesen/nagyon lassan
4. Lásd a hibát

Mi az elvárt viselkedés?
Termék családot jelző rész össze csukódása, legalsó felirat teljes mértékben látszódása.

Screenshots
![Screenshot_20221230_134546_TheVR](https://user-images.githubusercontent.com/121673998/210073793-f5930c9e-6668-47f5-a260-95566583a187.jpg)
![Screenshot_20221230_134536_TheVR](https://user-images.githubusercontent.com/121673998/210073795-5f1d7179-a1b9-402c-802a-f47e3c1d450f.jpg)
![Screenshot_20221230_134515_TheVR](https://user-images.githubusercontent.com/121673998/210073797-c46de849-46f9-42bb-8b04-13eae2445c1c.jpg)

- Android: Android 13, One UI 5.0
- Samsung Galaxy S21 Ultra
- App Verzió 0.0.2
- Internet: wifi 5ghz, mobilnet 4G/5G

Bármi más amivel kiegészítenéd
Shop fülön túl nagyok a termékeket jelző képek minimálisan lehetne kissebb nagyon "zsúfolt" hatást kelt.

**Comment by magtamas** [comment]
Javítva. 1.0.1-ben már elérhető
