### ISSUE TITLE
Shopban a képek el vannak csúszva 

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#27]
**Írd le, hogy mit tapasztaltál**
Ha a shopban 2 termék jelenik meg egymás mellett és az egyik termék neve 1 sorral hosszabb, akkor a képek el vannak csúszva.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a Shop képernyőre
2. Görgess lejjebb.
3. Keress 2 olyan trrméket, ahol az egyiknek a neve több sorba törik.
4. Lásd a hibát

**Mi az elvárt viselkedés?**
A termékek képei, ha egymás mellett 2 jelenik meg, igazodjanak egymáshoz.

**A következő információk nagyon fontosak:**
- OS verzió: Android 11
- Készülék: Xiaomi Redmi Note 9 Pro
- App Verzió: 0.0.2
- Internet: WIFI, 4G

**Screenshots**
![Screenshot_2022-12-30-14-29-22-571_hu thevr fallback](https://user-images.githubusercontent.com/20354967/210076047-860788f2-f86d-4cb1-b27c-2af753c98a35.jpg)
![Screenshot_2022-12-30-14-29-32-104_hu thevr fallback](https://user-images.githubusercontent.com/20354967/210076066-5468dd4b-cbde-445d-956b-56823679b7f1.jpg)
![Screenshot_2022-12-30-14-29-36-241_hu thevr fallback](https://user-images.githubusercontent.com/20354967/210076078-f16d01d2-3762-4803-a4dc-11accd9dfc5a.jpg)

**Comment by magtamas** [comment]
Javítva. 1.0.1-ben elérhető
