### ISSUE TITLE
Az értesítési sáv tartalma feketére vált és nem olvasható

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#28]
**Írd le, hogy mit tapasztaltál**
Az értesítési sáv (idő, töltöttség...) a splash screenen még fehér, de ahogy betölt az app, átvált feketére.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj bármelyik képernyőre
2. Nézd az értesítési sávot.

**Mi az elvárt viselkedés?**
Az értesítési sáv tartalma legyen fehér ugyanúgy, mint a splash screenen.

**A következő információk nagyon fontosak:**
- OS verzió: Android 11
- Készülék: Xiaomi Redmi Note 9 Pro
- App Verzió: 0.0.2
- Internet: WIFI, 4G

**Video**
https://user-images.githubusercontent.com/20354967/210077836-a777fd54-e775-4737-9ef6-6851b1dd9633.mp4

**Comment by iujlaki** [comment]
Javítva!
