### ISSUE TITLE
Dark mode-ban eltérnek a színek

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#29]
**Írd le, hogy mit tapasztaltál**
Ha az android dark mode-ját használom, több helyen is gond van a színekkel:
1. A splash screenen a VR logó szürkébb
2. Az értesítési sáv tartalma a rendszer light mode-jától eltérően nem fekete, hanem fehér.
3. A beállítások gombja fekete.
4. A shopban a termékek képe fekete lesz, ha a kép háttere fehér.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Válts dark modera
2. Indítsd el az appot
5. Menj a Shop képernyőre.

**Mi az elvárt viselkedés?**
Dark mode-ban ne változzanak meg az app színei

**A következő információk nagyon fontosak:**
- OS verzió: Android 11
- Készülék: Xiaomi Redmi Note 9 Pro
- App Verzió: 0.0.2
- Internet: WIFI, 4G

**Screenshot**
![Screenshot_2022-12-30-15-33-29-085_hu thevr fallback](https://user-images.githubusercontent.com/20354967/210081550-bbb4ade2-2b9e-4a99-b026-f03f88c39e7d.jpg)
![Screenshot_2022-12-30-15-33-42-474_hu thevr fallback](https://user-images.githubusercontent.com/20354967/210081572-d87b1005-1489-4e90-a2ba-295a1adfe066.jpg)
![Screenshot_2022-12-30-15-33-46-722_hu thevr fallback](https://user-images.githubusercontent.com/20354967/210081603-c0700c6d-1a63-4aff-b270-dc7959feec8b.jpg)

**Comment by magtamas** [comment]
Javítva. 1.0.1-ben elérhető
