### ISSUE TITLE
Értesítések képrenyő infinite loading-ol

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#3]
**Írd le, hogy mit tapasztaltál**
Ha az értesítések nincsenek bekapcsolva az app-ban, az értesítések screen infinite loadingol. Előtte egy pillanatra megjelenik valamilyen kontent.

**Hogyan tudjuk reprodukálni / előidézni?**
1. Menj az értesítések képernyőre.
2. Egy pillanatra megjelenik valamilyen kontent, majd infinite loadingol a képernyő

**Mi az elvárt viselkedés?**
Ha van tartalom az jelenjen meg, ha nincs akkor valamilyen empty screen.

**Video**
https://user-images.githubusercontent.com/20354967/209338931-7f9a8097-b836-4ac0-8e3a-54adc34de096.mp4

**A következő információk nagyon fontosak:**
- OS verzió: Android 11
- Készülék: Xiaomi Redmin Note 9 Pro
- App Verzió: 0.0.1
- Internet: WIFI, 4G

**Comment by prefector** [comment]
Oneplus 9, android 13 - ugyanez a probléma, egy pillanatra látszik mintha lenne egy doboz értesítés, de eltűnik azonnal és pörög a töltés animáció

**Comment by Errorhybrid** [comment]
POCO F2 Pro szintén zenész
OS: Android 12 SKQ1.211006.001 (2022.09.01. Security patch)
Verzió: 0.0.1
Internet: 4G

**Comment by Peredat0r** [comment]
Samsung s21 FE, ugyanez a gond ;)
Os: android 13, security patch: 2022 november 1
App 0.0.1
Internetek: wifi6 & 4G

**Comment by iujlaki** [comment]
Ez közben javítva lett 🙏
