### ISSUE TITLE
Beállítások ablak nem csukódik be valamelyik menüpontra kattintva 

### ISSUE THREAD

**Issue by Elod-T** [teamcodeyard/thevrapp-tracker#30]
**Írd le, hogy mit tapasztaltál**
Androidon ha a beállításokról úgy akarok elváltani, hogy egy alsó menüpontra nyomok, majd onnan visszamegyek arra a menüre ahonnan indultam akkor ott a tartalom helyett a beállítások lesznek. Emellett ha a beállításoknál arra a menüre nyomok lent, amin éppen voltam, akkor csak egyszerűen nem csukódik be. 

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a beállításokra a fogaskerékkel
2. Kattints valamelyik menüpontra a képernyő alján 
3a. Ha arra a menüre nyomtál ahonnan megnyitottad a beállításokat, akkor nem fog bezáródni a beállítások ablaka.
3b. Ha bármelyik másikra nyomtál akkor átvisz arra az oldalra. Viszont ha vissza akarsz menni az előző oldalra, akkor a beállítások fogadnak.

**Mi az elvárt viselkedés?**
Az előbbi '3a' esetben be kéne csukódnia a beállításoknak
A '3b' esetben pedig szintén be kéne csukódnia a beállításoknak, hogy amikor visszamegyek akkor a tartalom legyen ott.

**Screenshots**
https://user-images.githubusercontent.com/33983644/210090398-92922267-4768-4266-9c9e-d24474d8fc7d.mp4

**A következő információk nagyon fontosak:**
- OS verzió: Evolution X Android 13 
- Készülék: Xiaomi mi a3
- App Verzió: 0.0.2
- Internet: wifi

**Bármi más amivel kiegészítenéd**

**Comment by DavidKoth1** [comment]
Köszi a jelzést! Erről már tudunk, igyekszünk is javítani.
Addig is egy kis plusz infó, ha a beállításokból a visszalépésre az android vissza gombját használod, akkor az előző képernyőre jutsz vissza.

**Comment by iujlaki** [comment]
Átírtuk így már nem áll fenn a hiba, köszi 🙏
