### ISSUE TITLE
A shopban 1 termék fotója nem megfelelő

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#31]
**Írd le, hogy mit tapasztaltál**
A winter 2022 női póló képe nem megfelelő. A képen egy fekete reflective pulcsi van.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a Shop képernyőre
2. Görgess le a Winter 2022 női pólóhoz
2. Tappolj a  termékre
4. Lásd a hibát

**Mi az elvárt viselkedés?**
Az apoban a terméknél a hozzá tartozó kép jelenjen meg.

**A következő információk nagyon fontosak:**
- OS verzió: Android 11
- Készülék: Xiaomi Redmi Note 9 Pro
- App Verzió: 0.0.3
- Internet: WIFI, 4G

**Comment by iujlaki** [comment]
Ezek csak teszt adatok, de köszi, javítva
