### ISSUE TITLE
A shopban 1 termék rossz helyre irányít

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#32]
**Írd le, hogy mit tapasztaltál**
A shooban a Stealth reflective cipzáros pulóver rossz termékre, a Faces - Limited pólóra irányít át.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a Shoo képernyőre
2. Swioe-olj a Stealth 2.0-ra
3. Görgess le a Stealth reflective cipzáros pulóverhez
4. Tappolj a termékre
5. Lásd a hibát.

**Mi az elvárt viselkedés?**
Ha az appban a Stealth reflective cipzáros pulóverre tappolok, akkor a webshopban ehhez a termékhez kerüljek.

**A következő információk nagyon fontosak:**
- OS verzió: Android 11
- Készülék: Xiaomi Redmi Note 9 Pro
- App Verzió: 0.0.3
- Internet: WIFI, 4G

**Comment by iujlaki** [comment]
Javítva.
