### ISSUE TITLE
IOS Inactive Settings

### ISSUE THREAD

**Issue by FHl0** [teamcodeyard/thevrapp-tracker#33]
Sziasztok!

IOS en sem működik a settingsen belül az értesítés bekapcsolása.

Illetve az impresszum is inaktív még:)

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a settings képernyőre
2. Tappolj a  Menetrend,Social, Impresszum gombra
3. Görgess le a '....'-ra
4. Lásd a hibát

**Mi az elvárt viselkedés?*

Aktív legyen

**Screenshots**
Ha tudsz akkor csatolj képernyőképet, hogy megkönnyítsd a munkánkat.

**A következő információk nagyon fontosak:**
- OS verzió  iOS 15.7.1
- Készülék  iPhone 7
- App Verzió 0.1.0 build 9
- Internet:  WIFI

**Bármi más amivel kiegészítenéd**
Kíváncsiak vagyunk a véleményedre, kérlek írd le, hogy mit gondolsz az alkalmazásról?

Azon kívül, hogy szép munka, talán egy picivel nagyobb betűméretet adnék.

**Comment by DavidKoth1** [comment]
Köszi a jelzést! 
Az értesítések bekapcsolása egyelőre még le, de ezt a ticketet itt hagyom, hogy mások is lássák majd.
Illetve a betűméret miatt tettem rá egy 'enhancement' labelt, hogy ez nekünk is szem előtt maradjon.

**Comment by FHl0** [comment]
Nagy kedves tőled, köszi:)

Az iPhone-omról küldve

**Comment by iujlaki** [comment]
A 12-es build-be engedélyezve lettek a beállítások, az Impresszum még nincs kész de nekünk ez fel van írva.

A szövegezésnek, betűméretnek veszek fel egy külön issue-t, hogy nézzük át kiadás előtt, köszönjük az észrevételt 🙏
Ezt az issue-t zárom
