### ISSUE TITLE
Menetrend "Ma" gomb

### ISSUE THREAD

**Issue by cubixx** [teamcodeyard/thevrapp-tracker#35]
**Írd le, hogy mit tapasztaltál**
Menetrend "ma" gombja mindig keddre navigál. De ma hétfő van.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Menetrend' képernyőre
2. Tappolj a  'Ma' gombra
3. A keddi menetrend lesz látható
4. Ma hétfő van. (Jan. 2)

**Mi az elvárt viselkedés?**
Hétfőre kellene navigálni.

**A következő információk nagyon fontosak:**
- OS verzió: Android 9
- Készülék: OnePlus 3
- App Verzió: 0.0.3
- Internet: Wifi

**Comment by DavidKoth1** [comment]
Köszi a jelzést!

Nálam ez megfelelően működik:
- OS verzió: Android 11
- Készülék: Xiaomi Redmi Note 9 Pro
- App Verzió: 0.0.3
- Internet: WIFI, 4G

**Comment by cubixx** [comment]
Megnéztem ma is. Ma szerdára dob. Mikor megnyitom a menetrendet, eleve szerdán van, majd elnavigalok másik napra, megnyomom a "Ma" gombot, és visszaugrik szerdára. Próbáltam üríteni a cache-t, meg az app storage-t, de ugyanez van.

**Comment by iujlaki** [comment]
Fixálva
