### ISSUE TITLE
Délutáni streameknél időeltolódás

### ISSUE THREAD

**Issue by Kiskacske** [teamcodeyard/thevrapp-tracker#36]
**Írd le, hogy mit tapasztaltál**
A délutáni streamek 1 órával csúsztatva vannak a weboldalon található menetrendhezbképest.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a menetrendek képernyőre
2. Tappolj az adott nap gombjára
3. Lásd a hibát

**Mi az elvárt viselkedés?**
Pontos kezdés megjelenítése

**Screenshots**
![4DFB5D50-8FFC-4A2C-A7E3-109CA2D57FE5](https://user-images.githubusercontent.com/121851526/210313100-5c6d5c8d-5f26-4dc2-857a-ab86fa367bc4.png)
![D4D57E0D-CFE3-442D-AF5A-4014796A1FDF](https://user-images.githubusercontent.com/121851526/210313110-42aaa462-ba48-4e61-bad9-d047372c37f2.png)

**A következő információk nagyon fontosak:**
- OS verzió iOS 16.2
- Készülék iPhone 13
- App Verzió 0.1.0
- Internet Wifi

**Comment by iujlaki** [comment]
A mobilok hibája volt ez de javítva lett.
