### ISSUE TITLE
Értesítés csúszás

### ISSUE THREAD

**Issue by Peredat0r** [teamcodeyard/thevrapp-tracker#38]
**Írd le, hogy mit tapasztaltál**
Stream kezdés értesítése csúszással érkezik. (a Twitch noti korábban jött) 
Minden permissiont megadtam amit kért az app, csatoltam screenshotot is :)
Ha szerver resource miatti probléma ez, akkor nyugodtan zárjátok, csak jelezni akartam. 

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Várd meg a stream kezdetét
2. Várd meg a notificationt
**Mi az elvárt viselkedés?**
Stream kezdetekor jelezzen. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13609196/210508831-71fa4944-ce93-49f7-b700-c1480422974e.png)

**A következő információk nagyon fontosak:**
- OS verzió: Android 13 2022.12.01 frissítés 
- Készülék: Samsung S21 FE
- App Verzió 0.0.3
- Internet: Wifi

**Bármi más amivel kiegészítenéd**
Eddig nagyon tetszik, ez a funkció nekem fontos lenne, hogy lelőhessem a Twitch többi értesítését a követések leállítása nélkül ;) meló közben jó lenne.

**Comment by iujlaki** [comment]
Igen, 5 percenként fut jelenleg a job, viszont ha 8:30:05-kor lefut de Janiék csak 8:30:15-kor lövik be a streamet akkor legközelebb 8:35:00-kor fog megint lefutni.
Ész nélkül nem akarjuk futtatni mert naponta 3-4 alkalom van amikor tényleg jelezni fog, de bele szeretnék rakni valami okosságot pl: minden fél óra első 5 percében fusson le percenként vagy figyelni a menetrendet.
Mindegy is az észrevétel jogos, marad addig, köszi :)

**Comment by Peredat0r** [comment]
> Igen, 5 percenként fut jelenleg a job, viszont ha 8:30:05-kor lefut de Janiék csak 8:30:15-kor lövik be a streamet akkor legközelebb 8:35:00-kor fog megint lefutni. Ész nélkül nem akarjuk futtatni mert naponta 3-4 alkalom van amikor tényleg jelezni fog, de bele szeretnék rakni valami okosságot pl: minden fél óra első 5 percében fusson le percenként vagy figyelni a menetrendet. Mindegy is az észrevétel jogos, marad addig, köszi :)

Köszi Maestro!
Nincs olyan megoldás, hogy mikor indítják a streamet, akkor küld az appnak egy triggert az ő gépük? Egyszerűbb lenne mint jobot futtatni minden 5 percben. Egy plusz gombra rányomnak, vagy nemtom.

**Comment by iujlaki** [comment]
Én nem merek semmit az ő gépükre rakni 😅
Egyébként meg fogjuk oldani, nem nagy kihívás csak ki kell logikázni, szerencsére elég jól tartják magukat mindig a menetrendhez

**Comment by iujlaki** [comment]
Ez azt hiszem már zárható

**Comment by Peredat0r** [comment]
Igen, már pontosabb lett, megértem a concernt :) Agyaltam rajta, de nincs jobb megoldás valóban. 
Köszi!
