### ISSUE TITLE
Inventory-ban egymásra csúszó/nem látszódó kuponkódok

### ISSUE THREAD

**Issue by artschi-hun** [teamcodeyard/thevrapp-tracker#39]
**Írd le, hogy mit tapasztaltál**
Inventory/Együttműködéseink résznél, ha rányomok a kuponokra, akkor a 2. kuponkód rácsúszik a keretre - félbe is vágva a kódot, a 3. kuponkód nem is látszik, csak ha külön rányomok, de szintén félbevágva, így majdhogynem olvashatatlanná téve azt.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Inventory' képernyőre
2. Tappolj a  'CodeYard - 10% kedvezmény fejlesztése:' gombra

**Mi az elvárt viselkedés?**
Ha rákattintok a kuponokra, akkor görgetéssel is legyen látható mindegyik, valamint ne csússzonak rá a kód a keretre, lefelezve azt.

[**Screenshots**]
mellékelve

**A következő információk nagyon fontosak:**
- OS: Android 13
- Készülék: Samsung S21
- App Verzió 0.0.3
- Internet: mobilnet 4G
![thevr-01](https://user-images.githubusercontent.com/121974289/210634933-a3317996-2a17-4e04-a0dd-eaca2dfa66e6.jpg)

**Comment by DavidKoth1** [comment]
@artschi-hun Köszöjnük a jelzést! Arról már lett felvéve issue, hogy szétnyitás után nem megfelelően jelennek meg a kuponok, így ezt a ticketet lezárom. Ezt az issue-t ez alapján ofgjuk javítani:
https://github.com/teamcodeyard/thevrapp-tracker/issues/8

Viszont észrevettem a screenshotodon még 2 issue-t, azokat pedig felvettem külön, azok pedig ez alapján kerülnak majd javításra:
https://github.com/teamcodeyard/thevrapp-tracker/issues/44

**Comment by artschi-hun** [comment]
Szuper, köszi a javítást és a másik 2 észrevételt is :)
