### ISSUE TITLE
Beállítások képernyőn nincs cache ürítés

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#4]
**Írd le, hogy mit tapasztaltál**
Ha emgnézem a beállításokat, majd arra a képernyőre térnék vissza, ahonnan a beállításokhoz mentem, akkor a bellítások képernyő jelenik meg.

**Hogyan tudjuk reprodukálni / előidézni?**
1. Menj a Shop képernyőre.
2. Menj a beállításokba. (Megjelenik a beállítások képernyő és a tab bar-on továbbra is a Shop az aktív.)
3. Menj a menetrendre. Ekkor a menetrend jelenik meg.
4. Menj a Shop képernyőre. Ekkor a beállítások jelenik meg és a tab bar-on a Shop az aktív.
5. Menj a Menetrendre. Ekkor a Menetrend jelenik meg.
6. Menj a beállításokra. (Megjelenik a beállítások képernyő és a tab bar-on továbbra is a Menetrend az aktív.)
7. Menj a Hírekre. Ekkor a feed jelenik meg.
8. Menj a Menetrendre. Ekkor a beállítások jelennek meg és a tab baron a Menetrend az aktív.
9. Menj a Shop képernyőre. Ekkor a beállítások jelennek meg és a tab bar-on a Shop az aktív.
10. App adatok törlése után a megfelelő képernyők jelennek meg, amíg ismét meg nem nyitom a beállításokat.

**Mi az elvárt viselkedés?**
A beállítások megnyitása után ha egy másik képernyőre tappolok, akkor a kiválasztott képernyő tartalma jelenjen meg.

**Video**
https://user-images.githubusercontent.com/20354967/209341112-46d7c028-cc83-43ae-976f-c19105768f2b.mp4

**A következő információk nagyon fontosak:**
 - OS verzió: Android 11
 - Készülék: Xiaomi Redmin Note 9 Pro
 - App Verzió: 0.0.1
 - Internet: WIFI, 4G

**Comment by DavidKoth1** [comment]
Kiegészítés:
Ha az android vissza gombját használom visszalépésre, akkor a megfelelő screenre kerülök.

**Comment by iujlaki** [comment]
Átírva, így már jól viselkedik :)
