### ISSUE TITLE
Értesítések beállításai menü került a Hírek helyére

### ISSUE THREAD

**Issue by artschi-hun** [teamcodeyard/thevrapp-tracker#40]
**Írd le, hogy mit tapasztaltál**
A tesztelés során az egyik indításkor a Hírek menüpontra kattintva az Értesítések beállításai jelentek meg.

**Hogyan tudjuk reprodukálni / előidézni?**
Többször is próbáltam az app újraindításával előhozni, nem sikerült sajnos. Screenshot mellékelve.

![thevr-02](https://user-images.githubusercontent.com/121974289/210635465-6c39955a-d3c4-48a4-920e-3b5b56160e1c.jpg)

**Mi az elvárt viselkedés?**
A Hírek menüpontban a hírek jelenjenek meg.

**A következő információk nagyon fontosak:**
- OS: Android 13
- Készülék: Samsung S21
- App Verzió 0.0.3
- Internet: mobilnet 4G

**Bármi más amivel kiegészítenéd**
Kíváncsiak vagyunk a véleményedre, kérlek írd le, hogy mit gondolsz az alkalmazásról?

**Comment by DavidKoth1** [comment]
@artschi-hun Köszi a jelzést!
Ha jól sejtem ez ugyanaz az issue lesz, amit már korábban felvettünk.
Meg tudnád erősíteni, hogy így reprodukálható a hiba,?
1. Tappolj a Hírekre-re
2. Tappolj a beállításokra -> A beállítások jelenik meg
3. Tappolj a Menetrendere -> A Menetrendre kerülsz
4. Tappolj a Hírekre -> A beállítások jelenik meg.

Illetve azt is meg tudnád erősíteni, hogy a 4. lépés után, ha az android vissza gombjára tappolsz, akkor a Hírekhez kerülsz?

**Comment by artschi-hun** [comment]
Így van, igy lehet reprodukálni, illetve ez is így van - "a 4. lépés után, ha az android vissza gombjára tappolsz, akkor a Hírekhez kerülsz".

**Comment by DavidKoth1** [comment]
Nagyon köszi a gyors reakciót! Akkor ezt is lezárom, ez alapján az issue alapján kerül majd javításra: https://github.com/teamcodeyard/thevrapp-tracker/issues/4

**Comment by artschi-hun** [comment]
Szuper, köszönöm!
