### ISSUE TITLE
Értesítéseknél nem jelenik meg pár bejegyzésnél az időpont

### ISSUE THREAD

**Issue by artschi-hun** [teamcodeyard/thevrapp-tracker#41]
**Írd le, hogy mit tapasztaltál**
Értesítéseknél nem jelenik meg pár bejegyzés alatt a bejegyzés időpontja.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a "Értesítések' képernyőre
2. Lásd a hibát

**Mi az elvárt viselkedés?**
Látszódnia kellene minden bejegyzésnél, hogy mikor lett közzétéve.

**Screenshots**
Csatolva.

![thevr-03](https://user-images.githubusercontent.com/121974289/210636988-7fab5677-e018-40a0-a096-c8273755ac02.jpg)

**A következő információk nagyon fontosak:**
- OS verzió [Android 13]
- Készülék [Samsung S21]
- App Verzió [0.0.3]
- Internet [mobilnet, 5G]

**Comment by DavidKoth1** [comment]
Köszi a jelzést!
Ezt a ticketet lezárom, egy korábbi issue alapján kerül majd javításra: https://github.com/teamcodeyard/thevrapp-tracker/issues/16

**Comment by artschi-hun** [comment]
Rendben, köszönöm!
