### ISSUE TITLE
Dupla értesítés, Értesítés, Időeltolódás

### ISSUE THREAD

**Issue by DeerX8** [teamcodeyard/thevrapp-tracker#42]
**Írd le, hogy mit tapasztaltál**
Az app szerint ki vannak kapcsolva az értesítések, hiába nyomom a kapcsolókat, nem csinálnak semmit, mégis jön értesítés (iPhone beállításokba be vannak kapcsolva az értesítések)
Duplán küld értesítést.
Az összes stream 1 órával későbbre van ütemezve mint a valóságban, de az értesítés nincs későbbre ütemezve.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'főoldal' képernyőre
2. Tappolj a  'beállítások' gombra
3. tappalj a 'menetrend vagy social kapcsolókra'
4. Lásd a hibát

**Mi az elvárt viselkedés?**
A kapcsolóknak ki/be kéne kapcsolnia az értesítéseket.

**Screenshots**
Ha tudsz akkor csatolj képernyőképet, hog
![IMG_0936](https://user-images.githubusercontent.com/43912627/210779106-3f9b71b6-61f6-4f23-9bf4-a00e7ebb5189.PNG)
y megkönnyítsd a munkánkat.

**A következő információk nagyon fontosak:**
- OS verzió [pl. iOS 16.1.1]
- Készülék [pl. iPhone 11]
- App Verzió [0.1.1]
- Internet [pl.: WIFI, 4G]

**Bármi más amivel kiegészítenéd**
Kíváncsiak vagyunk a véleményedre, kérlek írd le, hogy mit gondolsz az alkalmazásról?

**Comment by iujlaki** [comment]
Köszi. Lezárom mert ma újra lett indítva a stream ezért ment két értesítés.

az eltolódott időre már van felvéve issue, a mai verzióval az javulni fog 🖖
