### ISSUE TITLE
menetrend változás esetén nem frissül 

### ISSUE THREAD

**Issue by kovi87** [teamcodeyard/thevrapp-tracker#43]
**Írd le, hogy mit tapasztaltál**
a menetrend változás esetén nem frissül, bent marad az eredeti stream is

**Screenshots**
![IMG_2140](https://user-images.githubusercontent.com/71906452/210836701-558b6625-cf00-4ab7-9a1c-21757c2909e9.PNG)

![IMG_2141](https://user-images.githubusercontent.com/71906452/210836725-9d3f8ce0-6048-4574-a200-93bd9465982c.PNG)

**A következő információk nagyon fontosak:**
- OS verzió ios 16.2
- Készülék  iPhone 13
- App Verzió 0.1.0 build9

**Comment by DeerX8** [comment]
+1 
iPhone 11
iOS: 16.1.1
app: 0.1.0 build10

**Comment by TaPi1224** [comment]
+1 Androidon is.

A srácok Discordon 13:01-kor küldtek értesítést menetrend változásról (jövő hetet kitöltötték), ez eddig (13:30) nem lett átvezetve az app-ban. Ezen túlmenően a mai napra vonatkozóan még mindig a fentebb látható második kép fogad, pedig napokkal ezelőtt törölve lett a High on Life stream.

Ahogy egy másik issue-ban is írják és a fenti képeken is látszik, a streamek időpontjai egy órával el vannak csúszva.

Huawei Mate 20 Pro
Android 11
app verzió: 0.0.3

**Comment by kovi87** [comment]
> Ahogy egy másik issue-ban is írják és a fenti képeken is látszik, a streamek időpontjai egy órával el vannak csúszva.

 ezt már javították a srácok. legalábbis ios-re tegnap jött frissítés

**Comment by TaPi1224** [comment]
> > Ahogy egy másik issue-ban is írják és a fenti képeken is látszik, a streamek időpontjai egy órával el vannak csúszva.
> 
> ezt már javították a srácok. legalábbis ios-re tegnap jött frissítés

Az Android verzió még csak a 0.0.3. verziónál jár, én ebből tudok kiindulni.

**Comment by TaPi1224** [comment]
Androidra megjelent a 0.0.4 verzió, amely javította az időzónás problémát, a menetrend azonban továbbra sem frissül. Jani beírta a honlapjukra péntek (január 13.) estére a horror streamet, az applikációban idáig (9:53) azonban még nem jelent meg.

Ezúton is köszi a CodeYard eddigi munkáját!

Huawei Mate 20 Pro
Android 11
app verzió: 0.0.4

**Comment by TaPi1224** [comment]
Most frissült, és bekerült a frissiben beírt ma esti CoD stream is. Így rendben van.

**Comment by iujlaki** [comment]
Köszi, javítottuk 🙏
