### ISSUE TITLE
Inventoryban a kupon betűmérete túl nagy

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#44]
**Írd le, hogy mit tapasztaltál**
Az inventoryban kisebb kijezőn (384 x 854 px) a kupon neve (képen: Footshop - 10% mindenre) nagy betűméret miatt nem fér rá teljesen.
A kuponoknál a komponensek alján és tetején van 1-1 kék sáv. 

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj az Inventory képernyőre
2. Tappolj a  kuponokra.

**Mi az elvárt viselkedés?**
Kisebb kijelzőn is megfelelően jelenjen meg a tartalom a kuponon hosszabb szöveg esetén.
A kuponok kisebb kijelzőn is megfelőlen jelenjenek meg.

**A következő információk nagyon fontosak:**
- OS: Android 13
- Készülék: Samsung S21 
- App Verzió 0.0.3
- Internet: mobilnet 4G

**Screenshots**
![210634933-a3317996-2a17-4e04-a0dd-eaca2dfa66e6](https://user-images.githubusercontent.com/20354967/210846733-75606f9d-4e47-4b7d-a01c-1a131d2b540d.jpg)

**Comment by iujlaki** [comment]
Ezt javítottam már, ha mégis előjönne nyissuk újra
