### ISSUE TITLE
Applikáció frissítés értesítés - de nincs újabb verzió a jelenleginél /0.0.4/

### ISSUE THREAD

**Issue by artschi-hun** [teamcodeyard/thevrapp-tracker#45]
**Írd le, hogy mit tapasztaltál**
A program dob egy értesítést, miszerint frissítsem a legfrissebb verzióra a kompatibilitási hibák elkerülése végett. A programot tegnap frissítettem a legújabb, 0.0.4 verzióra, ennél friseebbet nem mutat a Google Play.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Értesítések' képernyőre - látható az értesítés
2. Google Play-ben keress frissítést az applikációra
4. Lásd a hibát - nincs újabb frissítés a jelenleginél

**Mi az elvárt viselkedés?**
Csak akkor kapjak értesítést az app frissítésről, ha van újabb verzió a legfrissebbnél

**Screenshots**
![Screenshot_20230110_093253_TheVR](https://user-images.githubusercontent.com/121974289/211504747-65106e75-c7f3-44e4-9766-080815e51617.jpg)
![Screenshot_20230110_093243_TheVR](https://user-images.githubusercontent.com/121974289/211504830-c36ef493-f940-4635-9273-c8ad51996e88.jpg)

**A következő információk nagyon fontosak:**
- OS verzió [Android 13]
- Készülék [Samsung S21]
- App Verzió [0.0.4]
- Internet [mobilnet 4G]

**Comment by OlevO1** [comment]
IOS-re se jött ki, lehet hogy majd a jövőben érkezik

**Comment by iujlaki** [comment]
Ez egy általános üzenet volt, tehát mindenki megkapta, emlékeztetés hogy aki még nem tette meg az frissítsen.

**Comment by artschi-hun** [comment]
Nyilván, csak furcsa volt, hogy a frissítés után is ott marad, nem tűnik el. Ezért gondoltam arra, hogy akinél a legfrissebb verzió van, annál már ne jelenjen meg a frissítésre vonatkozó notification.

**Comment by iujlaki** [comment]
Igen, jogos csak nincs ilyen beépített funkció és valahogy el akartunk érni minél több embert. Reméljük a jövőben erre nem lesz szükség 🤘

**Comment by artschi-hun** [comment]
Értem, köszi a választ!
