### ISSUE TITLE
Hiányzó színkódok a menetrendben

### ISSUE THREAD

**Issue by Nickname1122** [teamcodeyard/thevrapp-tracker#47]
**Írd le, hogy mit tapasztaltál**
Az egyes eventek a 'menetrend' képernyõn default színt kapnak, valszeg az új weboldal miatt.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Menetrend' képernyőre
2. Lásd a hibát

**Mi az elvárt viselkedés?**
Legyenek színkódolva az eventek.

**Screenshots**
![image](https://user-images.githubusercontent.com/52052947/212696253-e4ea77fc-fac5-46ea-85ac-553b46c8e8fe.png)

**A következő információk nagyon fontosak:**
- OS verzió: iOS 16.3 (public beta)
- Készülék: iPhone 12
- App Verzió 0.1.0 (12)
- Internet: 5G

**Comment by zsoltpete** [comment]
@DavidKoth1 
Androidon nem tapasztalod ezt a hibát? Én úgy látom hogy ezt küldi a szerver(legyen szürke)

**Comment by DavidKoth1** [comment]
@zsoltpete 
De, Androidon is tapasztalom, emiatt tettem rá az API labelt

**Comment by DavidKoth1** [comment]
Plusz még néhány észrevétel. Nem tudom mennyire kapcsolódnak ehhez:
2023.01.13+tól viszamenőleg minden nap van 1-2 színes elem.
2023.01.13-án az adások duplikálva vannak. Ezek ha jól emlékszem módosítva lettek. Vagy törölve és újra felvéve.
2023.01.13-án a törölt elemeknél, illetve visszamenőleg mindenhol hiányoznak a képek.
![Screenshot_2023-01-26-19-14-49-588_hu thevr fallback](https://user-images.githubusercontent.com/20354967/214928446-b9446abd-a70e-4228-812d-75c61e9fd874.jpg)

**Comment by iujlaki** [comment]
Új verzióval javul
