### ISSUE TITLE
Twitch integráció jeletkezés után crash

### ISSUE THREAD

**Issue by CzinkeM** [teamcodeyard/thevrapp-tracker#48]
**Írd le, hogy mit tapasztaltál**
A Twitch integrációs hitelesítés után, amikor az újratölt az applikáció a képernyőt elforgatva crash-sel az app.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Inventory' képernyőre
2. Tappolj a  'Jelentkezés' gombra (Sorsolás)
3. Hitelesítsd magad
4. Amint újratölt az alkalmazás, forgasd el az eszközt
5. (Crash)

**Mi az elvárt viselkedés?**
Bármi gond nélkül lehessen forgatni az eszközt.

**A következő információk nagyon fontosak:**
- OS verzió: Android 9, Android 13
- Készülék: Huawei P20 Lite, Pixel 4XL
- App Verzió: 0.0.6,
- Internet: Wifi, 4G

**Bármi más amivel kiegészítenéd**
Kíváncsiak vagyunk a véleményedre, kérlek írd le, hogy mit gondolsz az alkalmazásról?
Szuperek vagytok, keep up the good work! :)

**Comment by iujlaki** [comment]
Fixálva, köszi 🙏
