### ISSUE TITLE
Nem nyílik meg az App

### ISSUE THREAD

**Issue by botix4** [teamcodeyard/thevrapp-tracker#49]
**Írd le, hogy mit tapasztaltál**
A 0.0.4es verzió óta nem engedett frissülni, most a 0.0.7re magától frissült, de a leírásban megadott funkciók nem mindegyike jelent meg. Uninstall és install után nem akar megnyilni, csak a logó jön fel, majd kilép.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Koppints az ikonra
2. És már látszik is

**Mi az elvárt viselkedés?**
Megnyílik hiba nélkül. Majd a már implementált funkciók legalább megjelennek.

**A következő információk nagyon fontosak:**
- OS verzió : Android 11, One UI 3.1
- Készülék : Samsung Galaxy A70
- App Verzió : 0.0.7
- Internet : WIFI, 4G

**Bármi más amivel kiegészítenéd**
Ma reggel (2023.01.31.) volt egy dev üzenet, hogy lesz valami az appal, de sajnos nem tudom pontosan mi, mert nem nyílik meg az app. Szóval, ha ahhoz van köze, akkor ez a hiba tárgytalan.

**Comment by botix4** [comment]
![Screenshot_20230202-152122_TheVR](https://user-images.githubusercontent.com/43544061/216350426-e99087dd-8511-4173-8c4d-21a0912b123a.png)

**Comment by iujlaki** [comment]
"Clear data" kellett hozzá, streamben lebeszéltük @botix4 -al 🙏
