### ISSUE TITLE
A képek nem töltenek be a shop fülön

### ISSUE THREAD

**Issue by OlevO1** [teamcodeyard/thevrapp-tracker#50]
**Írd le, hogy mit tapasztaltál**
A képek nem töltenek be a shop fülön

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Shop' képernyőre
2. Lásd a hibát

**Screenshots**
![image](https://user-images.githubusercontent.com/95526844/216814634-9dcb9847-ea72-44f3-84fe-fa2538874700.png)![image](https://user-images.githubusercontent.com/95526844/216814732-c96f788b-0af4-4043-82e6-7efe8a17a70d.png)
![image](https://user-images.githubusercontent.com/95526844/216814741-4d3f5d3a-210a-452f-8e02-6ac4868ef47c.png)

**A következő információk nagyon fontosak:**
- OS verzió iOS 16.3
- Készülék iPhone 13
- App Verzió 0.1.0 build 15
- Internet WiFi

**Comment by iujlaki** [comment]
Ez az új webshop miatt volt. Javult.
