### ISSUE TITLE
Hírek menüben Timeout szűrés nem működik

### ISSUE THREAD

**Issue by Timul00** [teamcodeyard/thevrapp-tracker#51]
**Írd le, hogy mit tapasztaltál**
Hírek menüben ha a szűrőknél mindent kikapcsolok csak a Timeoutot hagyom bekapcsolva nem jelenik meg tartalom.
Viszont ha minden szűrőt kikapcsolok akkor Timeout is megjelenik a hírfolyamban.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a hírek menübe
3. Minden szűrő legyen kikapcsolva kivéve a timeout
4. Megjelenik, hogy nincs tartalom
5. Módosítsd a szűrőket, minden szűrő legyen kikapcsolva (a timeout is)
6. Megjelenik minden tartalom, a timeout is

**Mi az elvárt viselkedés?**
Ha a szűrőknél a timeout be van kapcsolva, a hírek között jelenjen meg az a tartalom

**Screenshots**
![timeout](https://user-images.githubusercontent.com/52236707/217280538-124190f7-9931-46bb-81f6-5b2f73d2adbe.png)

**A következő információk nagyon fontosak:**
- OS verzió 16.3
- Készülék iphone 12mini
- App Verzió 0.1.0 (build 16)
- Internet WIFI / 4G

**Bármi más amivel kiegészítenéd**
Egyebet nem tudok mondani, kérem kapcsolja ki

**Comment by iujlaki** [comment]
Köszi, mostmár megy
