### ISSUE TITLE
Híreknél a szűrőben a Gaming+ ikon nem jó

### ISSUE THREAD

**Issue by Timul00** [teamcodeyard/thevrapp-tracker#52]
**Írd le, hogy mit tapasztaltál**
Ha megnyitom a hírek szűrőt a Gaming+ szűrőnél nem a lila ikon van mint a hírfolyamban.

**Hogyan tudjuk reprodukálni / előidézni?**
-

**Mi az elvárt viselkedés?**
A Gaming+ szűrőnek is olyan ikonnak kéne lenni mint a hírfolyamban a Gaming+ tartalomnál.

**Screenshots**
![gaming_logo](https://user-images.githubusercontent.com/52236707/217288049-3bf9d0a1-869b-4602-b9f0-640563ac9638.png)

**A következő információk nagyon fontosak:**
- OS verzió 16.3
- Készülék iphone 12mini
- App Verzió 0.1.0 (build 16)
- Internet WIFI / 4G

**Bármi más amivel kiegészítenéd**
-

**Comment by iujlaki** [comment]
Ezt a youtube fiókból rántjuk át, ott nem frissült még de az appba Jani már az új ikont küldte el a szűrőhöz
