### ISSUE TITLE
Híreknél a szűrők kapcsolgatásával helytelen tartalom jelenik meg

### ISSUE THREAD

**Issue by Timul00** [teamcodeyard/thevrapp-tracker#53]
**Írd le, hogy mit tapasztaltál**
Híreknél a szűrők kapcsolgatásával más tartalom jelenik meg mint amire rászűrtünk.
Ha frissítjük a hírfolyamot akkor megjavul.

**Hogyan tudjuk reprodukálni / előidézni?**
Videóban látszanak a lépések, de nem feltétlenül jön elő első körben, többször kell kapcsolgatni és megnézni mi jelenik meg.
Több módon is elő lehet hozni a hibát a videóban 2 esetet mutatok be.

**Mi az elvárt viselkedés?**
Csak az jelenjen meg a hírfolyamban ami a szűrőben be van kapcsolva

**Screenshots**
https://delage.hu/rpreplay_final1675784251.mp4

Az első hiba, hogy a Gaming szűrő van bekapcsolva, majd azt kikapcsolom és bekapcsolom a Twittert, de amikor bezárom a szűrőket akkor mégis a Gaming híreket látom.
A második pedig az, hogy a Timeout és a Shortcut is be van kapcsolva, majd a Shortcut-ot kikapcsolom de mégis megjelenik a hírfolyamban az is.

**A következő információk nagyon fontosak:**
- OS verzió 16.3
- Készülék iphone 12mini
- App Verzió 0.1.0 (build 16)
- Internet WIFI / 4G

**Bármi más amivel kiegészítenéd**
-

**Comment by iujlaki** [comment]
Ez a végleges verzióban javult, ha mégse kérlek jelezd 🙏
