### ISSUE TITLE
Kapcsoló viselkedése bug

### ISSUE THREAD

**Issue by OlevO1** [teamcodeyard/thevrapp-tracker#54]
**Írd le, hogy mit tapasztaltál**
Nem nagy hiba de, amikor a hírek fülön a bármelyik kapcsolót kapcsolgatom néha bebugol és kapcsol egyet magától is, ez látható a videón is.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Hírek' képernyőre
2. Tappolj a  'beállítások' gombra
3. Kapcsolgasd a bármelyik ON/OFF kapcsolót
4. Lásd a hibát

**Screenshots**

https://streamable.com/wahxac

**A következő információk nagyon fontosak:**
- OS verzió iOS 16.3
- Készülék iPhone 13
- App Verzió 0.1.0 Build 15
- Internet WiFi

**Comment by iujlaki** [comment]
Szia, azért van mert a szűrések async futnak (egymástól függetlenül) és ha az egyik később érkezik vissza mint az őt követő akkor felülírja a feltételeket.
Ezt javítottuk a végleges verzióban 🙏
