### ISSUE TITLE
Teljesen meghalt az app nálam

### ISSUE THREAD

**Issue by OlevO1** [teamcodeyard/thevrapp-tracker#55]
**Screenshots**

https://streamable.com/jvdi6y

**A következő információk nagyon fontosak:**
- OS verzió iOS 16.3
- Készülék iPhone 13
- App Verzió 0.1.0 build 15
- Internet WiFi

**Comment by iujlaki** [comment]
A bugot javitottuk, köszi. Érdemes újra telepíteni az alkalmazást hogy rendesen működjön
