### ISSUE TITLE
Értesítések frissülése

### ISSUE THREAD

**Issue by csaba-czako** [teamcodeyard/thevrapp-tracker#56]
Ha megjön az értesítés rányomok belelép az alkalmazásba de az értesítések nem frissülnek csak lehúzásra ios 16.3

**Comment by Zoshis85** [comment]
Sziasztok. Nagyon jó az app. Így tovább. 😎🤟😎
Egy észrevétel. Az utolsó 9 videó nem jelent meg a híreknél, és értesítés se jelent meg róla. Tudom, ma indult. Csak gondoltam szólok 😎
Android.
Szép estét 🤟😎

**Comment by iujlaki** [comment]
Elméletileg frissül viszont van olyan push amiről nincs inapp értesítés, pl a "Pereg a stream". Fenáll még ez nálad?

**Comment by csaba-czako** [comment]
Már nincs ilyen probléma, az általad kirakott értesítésre gondoltam, de ez is megszünt.
