### ISSUE TITLE
Értesítés / hírek nem frissül mindig 

### ISSUE THREAD

**Issue by Zoshis85** [teamcodeyard/thevrapp-tracker#57]
Sziasztok. Nagyon jó az app. Így tovább. 😎🤟😎
Egy észrevétel. Az utolsó 9 videó nem jelent meg a híreknél, és értesítés se jelent meg róla. Tudom, ma indult. Csak gondoltam szólok 😎
Android.
Szép estét 🤟😎

**Comment by Zoshis85** [comment]
És Jani láthatatlan lett.. 👍👍![Screenshot_2023-02-14-20-42-36-886_hu.thevr.app.jpg](https://user-images.githubusercontent.com/125402162/218841557-c99c0c0d-b374-443e-bd9a-026e90e999ec.jpg)

![Screenshot_2023-02-14-20-42-34-119_hu.thevr.app.jpg](https://user-images.githubusercontent.com/125402162/218841627-c7e40a34-e968-449a-913a-3059994f8d71.jpg)

**Comment by Zoshis85** [comment]
Happy Hour nál se jött értesítés most, belepve az appba is csak percekkel később. 😎

**Comment by Zoshis85** [comment]
![Screenshot_2023-02-15-16-52-40-616_hu.thevr.app.jpg](https://user-images.githubusercontent.com/125402162/219080169-18c8fc7f-7aac-4b34-ad33-27a0bb9b1f63.jpg)

**Comment by Zoshis85** [comment]
Jó reggelt 🤟👍
Nagyon jó az app. 2 értesítés jött reggel. De csak az egyik jelent meg ténylegesem az app van. Pisti Twitter üzenete.
A másik hogy újra működik minden azt nem találom.
Az élő adásrol viszont nem jött értesítés.
Menetrend se frissült még.

**Comment by Zoshis85** [comment]
3 új videó
![Screenshot_2023-02-16-19-38-48-256_com.google.android.youtube.jpg](https://user-images.githubusercontent.com/125402162/219457731-fbff1cfc-1487-4241-a5f6-4f0809eb716f.jpg)



. De appba nincs ott.
![Screenshot_2023-02-16-19-39-03-251_hu.thevr.app.jpg](https://user-images.githubusercontent.com/125402162/219457760-50b3ab93-7970-4568-b951-9277a6c60c66.jpg)

![Screenshot_2023-02-16-19-39-01-145_hu.thevr.app.jpg](https://user-images.githubusercontent.com/125402162/219457771-c2be9d71-d8e9-4254-b5b7-ff602e26455e.jpg)

**Comment by iujlaki** [comment]
Ez elviekben azóta megoldódott, köszi. Ha mégis látsz valami problémát, kérlek jelezd 🙏
