### ISSUE TITLE
Alsó menüsor tördelés nem jó

### ISSUE THREAD

**Issue by georgeczako** [teamcodeyard/thevrapp-tracker#58]
**Írd le, hogy mit tapasztaltál**
Alsó menüben 1-1 szó utolsó betűje új sorba csúszik

**Hogyan tudjuk reprodukálni / előidézni?**
Kezdőoldalon egyből látszik

**Mi az elvárt viselkedés?**
-

**Screenshots**
![55E39180-1F8B-494F-B5C7-679111291C7C](https://user-images.githubusercontent.com/42490933/218848529-a7a4be13-f6ce-4fbe-bab2-74ef6dd7c374.jpeg)

**A következő információk nagyon fontosak:**
- iOS 16.3
- iPhone 13 mini
- App Verzió 1.0.1
- Wifi, 5G

**Bármi más amivel kiegészítenéd**
-

**Comment by georgeczako** [comment]
Text size beállítás
![3C394D41-A809-46B0-90AC-338ED6D4D1D0](https://user-images.githubusercontent.com/42490933/219039990-8ebf4ab8-cf8c-4d1a-8643-a0801ae4b398.jpeg)

**Comment by iujlaki** [comment]
Köszi szépen, 1.0.2-es verzióban fog javulni
