### ISSUE TITLE
Nem játszódik le a GIF

### ISSUE THREAD

**Issue by OlevO1** [teamcodeyard/thevrapp-tracker#6]
**Írd le, hogy mit tapasztaltál**
Nem játszódik le a GIF az appon belül

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a 'Hírek' képernyőre
2. Görgess le 'TheVR Pisti posztjához (Képet csatolok hogy látszódjon melyikhez)'
4. A GIF első kép kockáját jeleníti csak meg

**Mi az elvárt viselkedés?**
Játssza le a GIF-et

**Screenshots**
![872ED9C6-17E2-49E8-96A8-C21046ADB4F6](https://user-images.githubusercontent.com/95526844/209434925-77073e1a-ddee-4fa4-9498-dc43553f1a92.png)

**A következő információk nagyon fontosak:**
- OS verzió || iOS 15.7.2
- Készülék || iPhone 7
- App Verzió || 0.1.0 build 5
- Internet || WiFi

**Comment by iujlaki** [comment]
Csak preview-t szinkronizálunk át (tehát se videót, se GIF-et), de a jövőben el lehet gondolkodni a GIF-en ezért ráraktam az enhancement tag-et
