### ISSUE TITLE
Az értesítések képernyőn nem mindig jelenik meg a profil kép

### ISSUE THREAD

**Issue by donpapa26** [teamcodeyard/thevrapp-tracker#60]
Androidon az értesítések menüben nem minden esetben jelenik meg a profilkép. 

Készítettem videót: https://drive.google.com/file/d/1eXZ_4_t4Y9P8Ijg9Hi02ycsX0u38Dv2J/view?usp=sharing

Android 11
One plus 7 pro
App verzió: 1.0.1

**Comment by iujlaki** [comment]
Javítva azóta, köszi 🙏
