### ISSUE TITLE
"Hírek" tabon Youtube posztoknál nincs HTML dekódolás

### ISSUE THREAD

**Issue by vereczkibalint** [teamcodeyard/thevrapp-tracker#61]
**Írd le, hogy mit tapasztaltál**
A "Hírek" tabon a Youtube videók esetén az esetlegesen címükben lévő speciális karakterek (idézőjel, és jel) nincsenek dekódolva.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a "Hírek" tabra.
2. Keress egy Youtube videót a feedben

**Mi az elvárt viselkedés?**
A speciális karaktereket dekódolni kell a megfelelőjüknek.
Pl.:
`&quot;` => "
`&amp;` => &

**Screenshots**
![yt_html_decode](https://user-images.githubusercontent.com/7327704/219389639-d12faa03-ab87-4125-9771-e2eb2cf96f88.jpeg)

**A következő információk nagyon fontosak:**
- OS verzió: iOS 16.3.1
- Készülék: iPhone 14 Pro Max
- App Verzió: 1.0.1 (build 1)
- Internet: Wifi

**Comment by iujlaki** [comment]
Javítva lett, köszi
