### ISSUE TITLE
Beállítások gomb fekete színű

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#64]
**Írd le, hogy mit tapasztaltál**
A beállítások gomb fekete színű, a szűrő, illetve minden más megfelelő színű.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj a Hírek képernyőre
2. Lásd a hibát

**Mi az elvárt viselkedés?**
A beállítások gombja is fehér színű legyen.

**Screenshots**
![Screenshot_2023-02-14-18-47-38-372_hu thevr app](https://user-images.githubusercontent.com/20354967/219973246-13547e05-5c08-4bbe-9600-4da347bc599f.jpg)

**A következő információk nagyon fontosak:**
- Készülék: Xiaomi Redmi Note 8 Pro

**Comment by DavidKoth1** [comment]
A hibát KDD jelezte discordon. Többen jelezték, hogy ugyanezt tapasztalják, viszont csak dark mode-nál.

**Comment by magtamas** [comment]
#29 issue-t duplikálja
