### ISSUE TITLE
Footshop kuponon felesleges ':'

### ISSUE THREAD

**Issue by DavidKoth1** [teamcodeyard/thevrapp-tracker#72]
**Írd le, hogy mit tapasztaltál**
Az inventoryban a Footshop kártyán maradt egy feleslegews ':'.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj az Inventory képernyőre
2. Lásd a hibát

**Mi az elvárt viselkedés?**
Ne legyen a kuponokon a leírás végén kettőspont.

**Screenshots**
![image0](https://user-images.githubusercontent.com/20354967/219975849-b1f85f90-024e-4646-8591-0c86d6d9afb3.png)

**Comment by DavidKoth1** [comment]
A hibát SIHL || Elnézést, nevetnem kell jelezte discordon

**Comment by iujlaki** [comment]
Javítva, köszönjük a művészi alkotást :D
