### ISSUE TITLE
Menetrend másnapra 

### ISSUE THREAD

**Issue by VJGY99** [teamcodeyard/thevrapp-tracker#75]
A menetrendben a másnapi eseményeknél mindig csak a HH jelenik meg, és hogy a többi program nincs benne.

Ezekkel a lépésekkel:
1. Menj a menetrend képernyőre
2. Tappolj a következő napra gombra
3. Lásd a hibát 

Screenshots:
![Screenshot_20230223_085252_TheVR.jpg](https://user-images.githubusercontent.com/80971475/220849872-07ff742a-c6ca-4118-b1c5-1c171799c5ae.jpg)

- OS verzió: Android 13, One UI 5.0
- Készülék: Samsung Galaxy A52s 5G
- App Verzió: 1.0.1
- Internet: wifi 5ghz, 5G

Egyébként elégedett vagyok vele, jó kis app!

**Comment by iujlaki** [comment]
Köszi, azért csak a HH látszik mert még a srácok nem töltötték ki a menetrendet a weboldalon. 
![939A09E8-1329-4E31-B4CF-53D76D7F763A](https://user-images.githubusercontent.com/429180/220861131-5bcd3241-fee1-43ef-9539-5fded6354c5d.png)

Egyébként a menetrend bizonyos időközönként frissül, előfordulhat h a weboldalon már fel van véve az új esemény de az appban még nem latszodik.

Zárom a ticketet és köszi a visszajelzést ✌️
