### ISSUE TITLE
Inventory visual bug

### ISSUE THREAD

**Issue by Errorhybrid** [teamcodeyard/thevrapp-tracker#8]
**Írd le, hogy mit tapasztaltál**
A képernyő alsó harmadában hirtelen véget ér a "hely" az inventory kártyáknak, így ha kinyitok egyet akkor nem néz ki túl esztétikusan a legalsó.

**Hogyan tudjuk reprodukálni / előidézni?**
Ezekkel a lépésekkel:
1. Menj az Inventory képernyőre
2. Tappolj bármelyik inventory kártyára
4. Lásd a hibát

**Mi az elvárt viselkedés?**
Ugyan olyan maradjon a kártyák mérete / legyen görgethető (most még nincs ennyi kártya)

**Screenshots**
https://user-images.githubusercontent.com/106850722/209550976-4432b0c2-91e9-4dd8-8772-2b2fc1871981.mp4

**A következő információk nagyon fontosak:**
- OS verzió: Android 12 SKQ1.211006.001
- Készülék: POCO F2 Pro
- App Verzió: 0.0.1
- Internet: 4G

**Comment by Peredat0r** [comment]
Samsung s21 FE, ugyanez látszik nálam is 
Os: android 13, security patch: 2022 november 1
App 0.0.1
Internetek: wifi6 & 4G
