### ISSUE TITLE
Internetelérés probléma

### ISSUE THREAD

**Issue by CzinkeM** [teamcodeyard/thevrapp-tracker#80]
Az app betöltése közben váltottam mobilnetről wifi-re. A betöltés után az app feldobja a "nincs internetelérés" dialog abalakot (lásd screenshot).
Ezután bármelyik hálózat konfigurációval próbálva feldobja az dialog ablakot és nem tölti be az adatokat.
Az internet elérést többször is ellenőriztem más applikációk tökéletesen működnek.
App adatok törlése , illetve újraindítás sem segített. Ami furcsább hogy újratelepítés után sem működik és ugyan ezt a hibát produkálja.

![Screenshot_20230621_085449_hu thevr app](https://github.com/teamcodeyard/thevrapp-tracker/assets/43544282/3e30aede-fb4c-47f9-9377-cf05014568f2)

**A következő információk nagyon fontosak:**
- OS verzió: Android 9
- Készülék: Huawei p20 lite
- App Verzió: 1.0.2
- Internet Wifi és 4G

**Comment by iujlaki** [comment]
Köszi szépen, azóta megoldódott :pray:
